app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, config/locales/ja.yml, config/routes.rb
userscontrollerを作成しました！
deviseでは標準でcontrollerが作成されていますが、カスタマイズするために
作成しました！余計なものも入ってます
=> userscontrollerの作成

app/controllers/users/invitations_controller.rb, app/helpers/users/invitations_helper.rb, app/models/invitation.rb, app/views/users/invitations/show.html.erb, config/routes.rb, db/migrate/20240107090746_create_invitations.rb, db/schema.rb, test/controllers/users/invitations_controller_test.rb, test/fixtures/invitations.yml, test/models/invitation_test.rb
invitaitonコントローラー作成しました！
招待URL発行できるようにしました！
=> invitaionコントローラー作成、招待URL発行

app/controllers/tops_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_before_login_header.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, tailwind.config.js
- 色のカスタマイズ
- ログインでのヘッダーの条件分岐
色のカスタマイズを反映したいので、レビューお願いします🙏
=> #1 create top page

app/controllers/groups_controller.rb, app/helpers/groups_helper.rb, app/views/events/index.html.erb, app/views/groups/_form.html.erb, app/views/groups/edit.html.erb, app/views/groups/index.html.erb, app/views/groups/new.html.erb, config/routes.rb, test/controllers/groups_controller_test.rb
groups controllerを作成しました。
- ルーティングのネストなどは考えれていません
groupテーブルについて、invitation_linkはカラム追加まだです。(型をどうするか相談させてください🙇‍♀️）
=> groups controllerの作成

app/assets/config/manifest.js, app/assets/stylesheets/custom.css, app/views/layouts/application.html.erb, app/views/tops/index.html.erb
普通のCSSを当てれるようにしました！ローカルでしか試してません！
=> cssを当てれるように変更

app/controllers/tops_controller.rb, app/controllers/users/registrations_controller.rb, app/helpers/application_helper.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_before_login_header.html.erb, app/views/shared/_header.html.erb, config/routes.rb
headerのボタンをクリックに修正しました。
[![Image from Gyazo](https://i.gyazo.com/8ebf8911d2a03826333c6c43d48b9c00.gif)](https://gyazo.com/8ebf8911d2a03826333c6c43d48b9c00)
.
[![Image from Gyazo](https://i.gyazo.com/65c4bf448f5b47ccf72a87e7dc0e0d85.gif)](https://gyazo.com/65c4bf448f5b47ccf72a87e7dc0e0d85)
※flashメッセージと新規登録画面は途中です
=> #19 sing up login

app/views/layouts/application.html.erb, app/views/shared/_header.html.erb, app/views/users/_settings_form.html.erb
view/users/settings_formのdivタグかけてたの直した泣泣
ハンバーガーメニューのz軸方向修正など
=> Correction

app/controllers/groups_controller.rb, app/views/groups/show.html.erb, app/views/shared/_header.html.erb
[![Image from Gyazo](https://i.gyazo.com/f0c20d03e488168257b0ffcdc2a7e6be.png)](https://gyazo.com/f0c20d03e488168257b0ffcdc2a7e6be)
=> グループメンバー一覧画面を作成し、整える

app/assets/stylesheets/custom.css, app/models/event.rb, app/views/events/index.html.erb, app/views/simple_calendar/_month_calendar.html.erb, config/application.rb, config/locales/activerecord/ja.yml, config/locales/views/ja.yml, db/migrate/20240111122326_rename_start_datetime_column_to_events.rb, db/migrate/20240111122421_rename_end_datetime_column_to_events.rb, db/schema.rb
- simple_calendarの特性上、start_datetimeカラム、end_datetimeカラムのカラム名をstart_time, end_timeへ変更しました🙇‍♀️
- 過去日のイベントは作成できないようにバリデーション追加しました（不要な場合は修正します）
- カレンダーの見た目を作成しました（今はlocalhost:3000/eventsで見れます。ちょこちょこ気になるところあり。）
どんなカレンダーにしたいかみんなのご意見いただけたら助かります🙏
=> Create calendars view

app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/controllers/groups_controller.rb, app/views/events/index.html.erb, app/views/groups/_group.html.erb, app/views/groups/index.html.erb, app/views/groups/new.html.erb, app/views/shared/_header.html.erb
グループを表示させて、グループ作成リンクから飛べるようにさせました！
=> Groupselection

app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/controllers/groups_controller.rb, app/views/events/index.html.erb, app/views/groups/_group.html.erb, app/views/groups/index.html.erb, app/views/groups/new.html.erb, app/views/groups/show.html.erb, app/views/shared/_header.html.erb
=> Membershow

app/views/devise/passwords/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_header.html.erb, app/views/tops/index.html.erb
- ログイン後headerにユーザー名を表示(不要であれば消します)
- passwordリセットをパスワードリセットへ変更
=> add:ログイン後headerにユーザー名を表示(不要であれば消します)

app/controllers/chats_controller.rb, app/helpers/chats_helper.rb, app/javascript/controllers/form_controller.js, app/models/chat.rb, app/models/group.rb, app/models/user.rb, app/views/chats/_chat.html.erb, app/views/chats/create.html.erb, app/views/chats/index.html.erb, config/routes.rb, db/migrate/20240114124857_create_chats.rb, db/schema.rb, test/controllers/chats_controller_test.rb, test/fixtures/chats.yml, test/models/chat_test.rb
- ログイン中のユーザーのchatは右側に、それ以外のユーザーのchatは左側に表示されるように条件分岐(動作確認未)
- 投稿したユーザーのプロフィール画像・ユーザー名、投稿時間が表示されるようにした
[![Image from Gyazo](https://i.gyazo.com/2475775a4a9bbc964fc51b29a89a0e0a.png)](https://gyazo.com/2475775a4a9bbc964fc51b29a89a0e0a)
【明日の作業予定】
- chat表示の条件分岐について動作確認を行う
- 見た目を整える
=> #50 chat機能実装

app/views/events/index.html.erb
=> chatpath追加

app/views/events/new.html.erb, app/views/groups/_form.html.erb
=> Formcorrection

app/helpers/events_helper.rb, app/views/events/edit.html.erb, app/views/events/index.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/groups/_form.html.erb, app/views/simple_calendar/_month_calendar.html.erb
=> event周辺ページのviewを修正しました

app/views/groups/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_user_setting.html.erb, app/views/users/_settings_form.html.erb
モーダルウィンドウの見た目と、グループメンバー一覧の＋ボタンの位置修正。
=> モーダルの見た目整える

app/views/shared/_header.html.erb
=> Revert "header修正"

app/views/shared/_user_setting.html.erb
[![Image from Gyazo](https://i.gyazo.com/8a70039749756035d72ce114c82d2826.png)](https://gyazo.com/8a70039749756035d72ce114c82d2826)
=> モーダル画面の閉じるボタンを変更

app/controllers/group_users_controller.rb, app/controllers/groups_controller.rb, app/controllers/permits_controller.rb, app/controllers/users/registrations_controller.rb, app/helpers/permits_helper.rb, app/helpers/user_groups_helper.rb, app/models/group.rb, app/models/permit.rb, app/models/user.rb, app/views/groups/new_permit.html.erb, app/views/groups/permits.html.erb, app/views/groups/show.html.erb, config/routes.rb, db/migrate/20240121014927_add_owner_id_to_groups.rb, db/migrate/20240121020354_create_permits.rb, db/schema.rb, test/controllers/permits_controller_test.rb, test/controllers/user_groups_controller_test.rb, test/fixtures/permits.yml, test/models/permit_test.rb
グループ参加機能を実装しました。
できること
グループ作成者はツイッターなどでリンクをシェアして、グループの参加を促せる
グループ参加希望の人は、リンクから申請ボタンを押して申請できる。
グループ作成者は承認ボタンをおして承認でき、その後、申請者はグループに参加できる。
グループ作成者（ホスト）は他の人を退出させることができるが、自分は退出できない
グループ削除ができるのは、ホストのみ
グループに所属してない人はそのグループは閲覧できない
=> Groupassign

app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_before_login_header.html.erb, app/views/shared/_header.html.erb, app/views/users/_settings_form.html.erb
=> Header周り修正

app/controllers/groups_controller.rb
グループコントローラー修正
- ホストはメンバーを退出させることができる。
- ホストは退出できないが、グループの削除はできる
=> グループコントローラ修正

app/controllers/group_users_controller.rb, app/controllers/groups_controller.rb, app/views/groups/permits.html.erb, config/routes.rb
=> Group users controller

app/controllers/group_users_controller.rb, app/controllers/groups_controller.rb, app/views/groups/permits.html.erb, app/views/groups/show.html.erb, config/routes.rb
=> Groupreqest

app/views/groups/_form.html.erb, app/views/groups/_new.html.erb, app/views/groups/edit.html.erb, app/views/shared/_header.html.erb
サイドバーからいつでもグループの新規作成ができるように実装。
[![Image from Gyazo](https://i.gyazo.com/018d522abca7bccf63798ebe23ab42bd.png)](https://gyazo.com/018d522abca7bccf63798ebe23ab42bd)
=> グループ作成画面をサイドバーに入れる

app/views/groups/_form.html.erb, app/views/groups/edit.html.erb, app/views/groups/new.html.erb, app/views/shared/_header.html.erb
=> Revert "グループ作成画面をサイドバーに入れる"

app/views/layouts/application.html.erb
=> フッターヘッター調整

app/views/events/daily_schedule.html.erb, app/views/groups/_form.html.erb, app/views/groups/_new.html.erb, app/views/groups/edit.html.erb, app/views/shared/_header.html.erb
[![Image from Gyazo](https://i.gyazo.com/666af7f623ba8105269cdbca5569c7ef.png)](https://gyazo.com/666af7f623ba8105269cdbca5569c7ef)
[![Image from Gyazo](https://i.gyazo.com/f511c96ef982db33225a971f284ec942.png)](https://gyazo.com/f511c96ef982db33225a971f284ec942)
=> グループ作成やり直し、日付ごとの予定画面整える

app/views/groups/show.html.erb
=> プロフィール画像表示エラー解消

app/views/events/daily_schedule.html.erb, app/views/groups/show.html.erb, app/views/users/events_for_date.html.erb
グループカレンダーの日付ごとの予定一覧
[![Image from Gyazo](https://i.gyazo.com/833bbd5b1e407acb023ebdc929cec050.png)](https://gyazo.com/833bbd5b1e407acb023ebdc929cec050)
マイページの日付ごとの予定一覧
[![Image from Gyazo](https://i.gyazo.com/93375e4579e57578adf657c9f1057dca.png)](https://gyazo.com/93375e4579e57578adf657c9f1057dca)
=> Edit views

app/models/user.rb, app/views/chats/index.html.erb, app/views/groups/new_permit.html.erb, app/views/groups/permits.html.erb, app/views/groups/show.html.erb, entrypoint.sh
=> Grouptable

app/views/chats/_form.html.erb, app/views/chats/index.html.erb
chatが無い(少ない)時もフォームが下部に固定されるように修正。
[![Image from Gyazo](https://i.gyazo.com/67c7735f105207bde681000970147c2b.gif)](https://gyazo.com/67c7735f105207bde681000970147c2b)
=> fix:フッター固定修正

app/assets/stylesheets/custom.css, app/views/events/_form.html.erb, app/views/events/_show.html.erb, app/views/events/index.html.erb, app/views/simple_calendar/_month_calendar.html.erb, app/views/users/show.html.erb
- カレンダーのレスポンシブ設定
- CSSの崩れを修正
- その他見た目の微修正
モーダル画面でのイベント作成・編集、グループ編集時のrender修正、フラッシュメッセージ表示についてはまだ対応できていません。
=> カレンダーのレスポンシブ設定、イベント関連viewの修正

app/controllers/events_controller.rb, app/controllers/groups_controller.rb, app/views/events/_form.html.erb
コントローラーを修正してRenderエラー解消
フラッシュメッセージ表示
=> モーダルのバリデーションメッセージ表示

app/views/events/_new.html.erb, app/views/shared/_header.html.erb, app/views/users/events_for_date.html.erb
[![Image from Gyazo](https://i.gyazo.com/b6cd403fe9febfad2356b7b099e67e40.png)](https://gyazo.com/b6cd403fe9febfad2356b7b099e67e40)
[![Image from Gyazo](https://i.gyazo.com/e9aaff434e93c40dd9250e8f8303f6ce.png)](https://gyazo.com/e9aaff434e93c40dd9250e8f8303f6ce)
[![Image from Gyazo](https://i.gyazo.com/75497ada189082c102b8006f14e01185.png)](https://gyazo.com/75497ada189082c102b8006f14e01185)
=> モーダル修正、Myカレンダーの見た目整える

app/models/event.rb, app/models/group.rb, app/views/events/_new.html.erb, app/views/events/_show.html.erb, app/views/groups/_form.html.erb, app/views/groups/_new.html.erb, app/views/tops/index.html.erb, app/views/users/_settings_form.html.erb
=> 文字数バリデーション設定。フォームに必須追加。ログアウトボタン切り替え

app/views/events/_form.html.erb
CSS少しだけ直して編集フォームとShowビューで位置が変わらないようにしました
=> イベント編集フォームのマージン修正

app/views/events/_form.html.erb
=> ひとつ前のコミットで間違って消した部分戻します

app/controllers/permits_controller.rb, app/models/group.rb, app/models/notification.rb, app/models/permit.rb, app/views/notifications/_notification.html.erb, db/migrate/20240125164414_add_permit_id_to_notifications.rb, db/schema.rb
グループ参加申請の通知はできました。
ただ、リンク先に遷移できてましたがターミナルが一度落ちてからリンク先に遷移されず、リンクを押すと`Content missing`と表示されるようになってしまいました。(今日いじっていない他の通知のリンクも)
眠くて頭回らないので明日修正します。
[![Image from Gyazo](https://i.gyazo.com/34fb9085dc51dabde4ae4c4c69d98724.gif)](https://gyazo.com/34fb9085dc51dabde4ae4c4c69d98724)
=> Notification fix

app/views/events/_form.html.erb
モーダルエラーメッセージも他と同じように表示されるようstyle追加しました。
[![Image from Gyazo](https://i.gyazo.com/243070b5c0b5aa90221eeadf7d00c1d2.png)](https://gyazo.com/243070b5c0b5aa90221eeadf7d00c1d2)
=> モーダルエラーメッセージのstyle追加

app/models/user.rb
=> 日別のマイイベント抽出コードを修正しました

app/views/layouts/application.html.erb
基本的なGoogleAnalyticsの設定を行いました。ご確認お願いします。
一度デプロイしないと動いているか確認できないみたいなので、お手隙の際にマージとデプロイお願いします🙇‍♀️
=> add:基本的なGoogleAnalyticsの設定完了
